---
# Per environment values which override defaults in make-recall-decision-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: consider-a-recall-dev.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    INGRESS_URL: "https://consider-a-recall-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    MAKE_RECALL_DECISION_API_URL: "https://make-recall-decision-api-dev.hmpps.service.justice.gov.uk"
    MAKE_RECALL_DECISIONS_AND_DELIUS_API_URL: "https://make-recall-decisions-and-delius-dev.hmpps.service.justice.gov.uk"
    SENTRY_ENVIRONMENT: "DEV"
    ENVIRONMENT: "DEVELOPMENT"
    FEATURE_FLAG_QUERY_PARAMETERS_ENABLED: true
    SHOW_NOTIFICATION: false
    NOTIFICATION_HEADER: "Scheduled Maintenance"
    NOTIFICATION_BODY: "This application will be unavailable between 12.00pm and 2.00pm on September 18th 2023, please save your work ahead of time."

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: make-recall-decision-nonprod

